version: "3"
services:
  web:
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  worker:
    build: ./worker
    restart: always
    command: python run.py
    environment:
      DEPLOYMENT: 'true'
    depends_on:
      - redis
  db:
    image: "postgres:13.1-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  redis:
    image: "redis:6.0.10-alpine"
    restart: always
    ports:
      - "6379:6379"
