version: "3"
services:
  worker:
    build: ./worker
    restart: always
    environment:
      DEPLOYMENT: 'true'
    depends_on:
      - redis
  db:
    image: "postgres:13.1-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: "redis:6.0.10-alpine"
    restart: always
    ports:
      - "6379:6379"
volumes:
  dbdata:
